### ISSUE TITLE
Error While running py.test

### ISSUE THREAD

**Issue by man2nainwal** [SalesforceFoundation/salesforce-streaming-client#2]
ImportError while importing test module '/root/Streaming/src/salesforce-streaming-client/tests/test_it.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
Streaming/src/salesforce-streaming-client/tests/test_it.py:33: in <module>
    from salesforce_streaming_client import SalesforceStreamingClient
E   ImportError: No module named salesforce_streaming_client

can you please tell me, where is problem ?

**Comment by whusterj** [comment]
The error message says that `salesforce_streaming_client` cannot be found (it's not in your PYTHONPATH). This is probably happening because you cloned the repository (as opposed to pip install) and did not add the `salesforce-streaming-client/src` directory to the path.

I would recommend using virtualenvwrapper that has the very convenient `add2virtualenv` command. Then you can go to the `salesforce-streaming-client/src` directory, run `add2virtualenv .` which will add the `src` directory to the Python path. Then try running the tests again.

**Comment by adamlincoln** [comment]
@man2nainwal did @whusterj 's comment help you out?  If not, please re-open this issue or feel free to open a new one.  Thanks!  (and thanks for @whusterj for jumping in!)
